//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int ids { get; set; }
        public string sname { get; set; }
        public Nullable<int> courseid { get; set; }
    
        public virtual courses course { get; set; }
    }
}
